### ISSUE TITLE
Review request

### ISSUE THREAD

**Issue by sammichaud** [sammichaud/GPR1-SocialNetwork#1]
@NicolasGlassey

https://github.com/sammichaud/GPR1-SocialNetwork/commit/7ada690bd1ad53f4ee321e0ad7ccdd8936e5eb72

**Comment by NicolasGlassey** [comment]
@sammichaud 

Bonjour Samuel,

J'ai bien reçu votre demande de review. Elle sera traitée soit aujourd'hui, soit lundi.

Cordialement

**Comment by NicolasGlassey** [comment]
@sammichaud 

A vous de jouer. La review a été faite !
