### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by sammichaud** [sammichaud/GPR1-SocialNetwork#3]
@NicolasGlassey
https://github.com/sammichaud/GPR1-SocialNetwork/commit/7afd013a48a00e8dac811c922ceda0b75118f0b0

Le test test_constructor_InstantiationWithDuplicatedSubscribers_ThrowsException ne passe pas.
Selon moi ce test est faux car il est censé tester l'instantiation d'un object Twitter prenant comme paramètre un tableau de followers avec des doublons à l'intérieur. Sauf qu'ici on ne lui donne un tableau qu'avec un seul follower donc sans doublon.

Pour corriger ce test il faudrait remplacer la ligne 58 ```$followersWithDuplicate = array();``` par ```$followersWithDuplicate = $followers;```. Comme ça on se retrouverait à tester un tableau de follower avec le première élement dupliqué et donc une erreur SubscriberAlreadyExistsException serait levé.

**Comment by NicolasGlassey** [comment]
@sammichaud 

Bonjour Samuel,

J'ai pris en compte cette issue pour l'évaluation.

Bonne suite de week-end !
